---
- hosts: all

  become: true

  pre_tasks:
    - user: name=app shell=/bin/bash
    - name: Set up authorized_keys for the app user
      authorized_key: user=app key="{{ item }}"
      with_file:
        - public_keys/mizokami

  roles:
    - { role: common }
    - { role: rbenv, ruby_version: 2.3.0 }

