---
- hosts: all

  become: true

  vars:
    common:
      user:
        name: app
        authorized_keys:
          - public_keys/mizokami.pub
    rbenv:
      ruby_version: 2.3.1

  roles:
    - common
    - rbenv
    - redis
