- name: Install dependencies
  yum:  name={{ item }} state=present
  with_items:
    - git
    - tar
    - gcc
    - make
    - libffi-devel
    - readline-devel
    - zlib-devel
    - openssl-devel

- name: Install rbenv
  git:  repo=git://github.com/rbenv/rbenv.git dest=/usr/local/rbenv version=v0.4.0

- name: Create symlink to rbenv
  file: path=/usr/local/bin/rbenv src=/usr/local/rbenv/bin/rbenv state=link

- name: Add rbenv initialization to profile
  template: src=templates/rbenv.sh.j2 dest=/etc/profile.d/rbenv.sh owner=root group=root mode=0755

- name: Install ruby-build
  git: repo=git://github.com/rbenv/ruby-build.git dest=/usr/local/rbenv/plugins/ruby-build version=master

- name: Install ruby {{ rbenv.ruby_version }}
  shell: RBENV_ROOT=/usr/local/rbenv /usr/local/rbenv/bin/rbenv install -s {{ rbenv.ruby_version }}

- name: Use ruby {{ rbenv.ruby_version }}
  shell: RBENV_ROOT=/usr/local/rbenv /usr/local/rbenv/bin/rbenv global {{ rbenv.ruby_version }}

- name: Install bundler
  shell: RBENV_ROOT=/usr/local/rbenv /usr/local/rbenv/bin/rbenv exec gem install bundler
